name: postgrest_crud
description: A Postgrest client that provides create, recall, update, and delete operations with support for batch operations via createBatch, updateBatch, and deleteBatch.
version: 0.1.3-dev.1
homepage: https://github.com/KernlAnnik/postgrest-crud-dart

environment:
    sdk: '>=2.18.5 <3.0.0'

dependencies:
    http: ^0.13.5

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0
    yaml: ^3.1.1
